name: dingo_prototype
description: a dingo prototype

version: 1.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_calendar_carousel: ^2.0.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.3
  webview_flutter: ^2.0.8
  simple_animations: ^1.3.9
  charts_flutter: ^0.10.0
  firebase_core: 1.2.1
  firebase_auth: 1.3.0
  cloud_firestore: ^2.2.1
  local_auth: ^1.1.6
  flutter_html: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/weather/
    - images/announcementMenu/
    - images/fingerprintIcon/
