name: dingo_prototype
description: a dingo prototype

version: 1.1.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_calendar_carousel: ^2.0.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.3
  webview_flutter: ^2.0.8
  simple_animations: ^4.0.1
  charts_flutter: ^0.12.0
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  local_auth: ^1.1.6
  flutter_html: ^2.1.0
  rxdart: ^0.27.3
  provider: ^6.0.1
  flutter_local_notifications: ^9.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/weather/
    - images/announcementMenu/
    - images/fingerprintIcon/
